### ISSUE TITLE
Swagger validation

### ISSUE THREAD

**Issue by Stephan-Ghequiere** [digipolisantwerp/swagger_aspnetcore#6]
Digipolis.Swagger configureert de api om OpenApi 3.0 te gebruiken om de swagger te genereren. 
Deze versie wordt echter niet ondersteund door openapi-validator.antwerpen.be.

Toolbox moet aangepast worden om terug Swagger 2.0 te gebruiken.

**Comment by erikseynaeve** [comment]
issues opgelost in toolbox v1.0.4
